[project]
name = "swissgeol-boreholes-photo-processor"
version = "0.1.0"
description = "Python project that generates composite images from photos of borehole cores and cuttings"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "imagecodecs>=2026.3.6",
    "matplotlib==3.10.9",
    "mlflow==3.13.0",
    "Pillow==12.2.0",
    "PyYAML==6.0.3",
    "scikit-image>=0.26.0",
    "tifffile>=2026.3.3",
    "tqdm==4.67.1",
]

[project.optional-dependencies]
test = [
    "pytest==8.4.1",
    "pytest-cov==6.2.1",
    "moto==5.1.10",
]

[dependency-groups]
dev = [
    "ruff",
    "ty",
    "pre-commit==4.3.0",
]

# ---- Configuration for package building
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[project.scripts]
boreholes-photo-processor = "src.run:main"

# ---- Configuration for Ruff
[tool.ruff.lint]
select = [
    # pydocstyle
    "D",
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = [
    "D102",  # Missing docstring in a public method
    "D104",  # Missing docstring in public package
    "D105",  # Missing docstring in magic method
    "D107",  # Missing docstring in `__init__`
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["D100", "D103"]  # Test modules and functions don't need module/function docstrings

[tool.ruff]
line-length = 119

[tool.ruff.lint.pydocstyle]
convention = "google"
